### PR TITLE
feat(@lion/ui): add _currencyDisplayNodeSlot to LionInputAmount

### PR DESCRIPTION
**Pull request by gyulus3**
## What I did

Added a _currencyDisplayNodeSlot variable to the LionInputAmount component to be able to customize the slot to put the currency label.

### CODE REVIEW

**Comment by gerjanvangeest** [comment]
Hi @gyulus3 thanks for the contribution.

Could you add tests and some documentation for this feature?

**Comment by gyulus3** [comment]
Hey @gerjanvangeest!

Of course, I can do that! Investigating the component I found something strange, what I believe is a leftover from a previous state of the code.

The currency label can be visible only in the _after_ slot as it is said in the code [here](https://github.com/ing-bank/lion/blob/master/packages/ui/components/input-amount/src/LionInputAmount.js#L182). But the [documentation of the LionInputAmount](https://github.com/ing-bank/lion/blob/master/docs/components/input-amount/use-cases.md) mentions that setting the currency attribute will set the currency _suffix_, what is a bit misleading.

Besides the tests of the component I found a [test case](https://github.com/ing-bank/lion/blob/master/packages/ui/components/input-amount/test/lion-input-amount.test.js#L197) for this situation and it says that it should ignore the display of the currency if the _suffix_ slot is already present. Indeed this test case succeeds because the currency is set in the _after_ slot and never overwrites the _suffix_ slot. Later I tested it with a little modification, where I put the currency in the _suffix_ slot, and when this slot was already set then the currency was still visible, which is the opposite behavior that the case wanted to test.

If you agree to this, I can fix the documentation with a little effort and remove the test cases that are not appropriate anymore.

**Comment by gerjanvangeest** [comment]
@gyulus3 That sounds like a great fix!

**Comment by gyulus3** [comment]
@gerjanvangeest I removed the inappropriate test case and created a new one for the requested feature. The docs have been updated, so the use-case contains now the customizable slot for the currency label.

**Review by gerjanvangeest — APPROVED** [review]

**Comment by gyulus3** [comment]
@gerjanvangeest when will be the next release? I would be glad if it would be available soon.

**Comment by gerjanvangeest** [comment]
Let me check with my team if we have anything else pending. Otherwise i'll make a release today/tomorrow.

**Pull request merged**
