### PR TITLE
fix: Allow elements with display:contents to be focusable in keyboard event trapping

### PR DESCRIPTION
**Pull request by stefanpearson**
I noticed an issue in overlays, where keyboard event trapping would skip certain focusable elements. After debugging for a while, I discovered that certain elements were deemed 'not visible' and would be skipped from the traversal if `display: contents` had been set. This is because of the check that is in place to explicitly query the box model as a last check, which would give a false negative.

This is problematic for when `display: contents` is important, and definitely has visible focusable elements within it!

## What I did

1. Added a check to see if `display: contents` is in the computed styles, and resolve `true`.

If anyone can think of a smarter check then I'm happy to change this. Perhaps querying the box model is not the right approach here anyway?

### CODE REVIEW

**Comment by jorenbroekema** [comment]
Looks good to me, thanks for contributing a fix. Probably wasn't too easy to find the code that was handling the focus trap.

Do you think it would make sense to add another test in `/pacakages/overlays/test/utils-test/get-focusable-elements.test.js` just as a smoke test, making sure that if there is a focusable element inside a parent element that has display: contents, it indeed caught by this util?

**Comment by stefanpearson** [comment]
> Do you think it would make sense to add another test in `/pacakages/overlays/test/utils-test/get-focusable-elements.test.js` just as a smoke test, making sure that if there is a focusable element inside a parent element that has display: contents, it indeed caught by this util?

Yep seems sensible; I've added this now.

**Comment by stefanpearson** [comment]
Thanks for the approval! What is the merge/publish process for these PRs? I've managed to use a workaround for now (removing `display: contents` for a certain component), but would be great to see this land soon.

**Comment by jorenbroekema** [comment]
I'm one of the maintainers but no longer working at ING so one of my ex-colleagues needs to put their approval as well in order to be able to merge. After that it can be released pretty much right away unless something else is holding up the release for some reason. @tlouisse @gerjanvangeest 

tomorrow is also Ascension Day so I suspect a fair few people are taking a long weekend off :)

**Review by gerjanvangeest — APPROVED** [review]

**Pull request merged**
