### PR TITLE
feat(core): add ScopedStylesMixin

### PR DESCRIPTION
**Pull request by jorenbroekema**
## What I did

1. Abstract the scoped styles functionality to a generic mixin, moving it from input-range to core package
2. Move tests pertaining to the scoped styles functionality in input-range to core as well
3. SkipLibCheck true until https://github.com/open-wc/open-wc/pull/2411 & https://github.com/open-wc/open-wc/issues/2388 are resolved

I have a use case where I could really use this scoped styles mixin:
I got a custom-element which relies on tailwind (global stylesheet) so I must use `createRenderRoot -> this` and make it render to LightDOM. However, there's custom styles that I'd still prefer to have scoped to prevent style conflicts/leakages.

### CODE REVIEW

**Comment by daKmoR** [comment]
I think that feature might be able to be implemented via an [Lit controller](https://lit.dev/docs/composition/controllers/)...

care to try it out?

**Comment by gerjanvangeest** [comment]
You also need to update the docs: https://github.com/ing-bank/lion/blob/cc281b505a8422381b4d3151ccad5122d75ddb5c/docs/components/inputs/input-range/features.md?plain=1#L95

**Comment by jorenbroekema** [comment]
Looks like I succeeded :)

**Review by gerjanvangeest — APPROVED** [review]

**Comment by jorenbroekema** [comment]
Ah crap I meant to squash and merge, 3 redundant commit messages now :P my bad

**Pull request merged**
