### PR TITLE
Ajax fetch error fixes

### PR DESCRIPTION
**Pull request by koddsson**
## What I did

1. I set the `name` property of the error so that the name is preserved. Without setting the `name` property it's overwritten when calling `super`.

### Input
```js
class MyError extends Error {
    constructor() {
        super('My error!')
    }
}
try { throw new MyError('foobar') } catch(err) { console.log(err.name) }
```

### Output
```
Error
```

Compare that with the same code where we actually set the `name` property:

### Input
```js
class MyError extends Error {
    constructor() {
        super('My error!')
        this.name = 'MyError'
    }
}
try { throw new MyError('foobar') } catch(err) { console.log(err.name) }
```

### Output
```
MyError
```

2. Added the response status code and text to the message.

### CODE REVIEW

**Comment by koddsson** [comment]
And what do you think about linting for this in the future?

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/6d15a02d48de7ecfc38d0683a8487b2f937d83a0/docs/rules/custom-error-definition.md

**Comment by tlouisse** [comment]
> And what do you think about linting for this in the future?
> 
> https://github.com/sindresorhus/eslint-plugin-unicorn/blob/6d15a02d48de7ecfc38d0683a8487b2f937d83a0/docs/rules/custom-error-definition.md

Seems like something that you would easily forget, so good idea to add the rule. Would you like to add a PR for it?

**Comment by koddsson** [comment]
@tlouisse; I think this latest change should be good but CI isn't running. You probably need to push the button again :)

**Comment by tlouisse** [comment]
> @tlouisse; I think this latest change should be good but CI isn't running. You probably need to push the button again :)

Awesome. We will merge it soon to master (master is currently in a 'prerelease mode', it will be merged when it's back in 'normal mode') and let you know when it will be released on npm.

**Pull request merged**
