### PR TITLE
feat(input-range): add input-range component

### PR DESCRIPTION
**Pull request by manolakis**
Creates the `lion-input-range` component.

This component extends `LionField` instead `LionInput` because `LionInput` contains the [readonly attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-readonly) that belongs to text input fields and the range is a numeric input that doesn't support it.

### CODE REVIEW

**Comment by manolakis** [comment]
I'm not able to run the tests again. It's strange because I run it several twice locally and it worked fine (I know, it's the typical phrase "it works in my machine" 😞). However, I would like to know the reason why the test failed. 🤔

**Comment by daKmoR** [comment]
browserstack was flacky yesterday - it works fine now so I rerun the test and it's green 🤗

**Comment by manolakis** [comment]
thanks @daKmoR! 👏

**Comment by manolakis** [comment]
Why are those deploys failing? do I need to do something in the PR? 🤔

**Comment by erikkroes** [comment]
We have a local contribution coming up which is more extensive. Closing this version.

**Pull request closed without merging**
