### PR TITLE
chore(pagination): extract nav list logic into protected method

### PR DESCRIPTION
**Pull request by hardikpthv**
## What I did

1. Extract the nav list template logic into a protected method so that the derived component can easily reuse it.

### CODE REVIEW

**Comment by daKmoR** [comment]
if you want this to be released then you will need to add a "changeset".

e.g. do `yarn changeset` then select pagination and to a fix release + add your message for the changelog.
this will create a md file you should commit (probably best to do `git commit --amend` to add it to this single commit)

PS: I think a commit message with `fix(pagination)` would be better

**Comment by hardikpthv** [comment]
Thanks, @daKmoR for the tip. I followed the steps you suggested. Do let me know if any changes are required.

**Comment by daKmoR** [comment]
oh can you move this to a "local" branch? e.g. not in your fork 😅

**Comment by hardikpthv** [comment]
There you go https://github.com/ing-bank/lion/pull/961

**Pull request closed without merging**
