### PR TITLE
feat(core): allow lit-html in SlotMixin

### PR DESCRIPTION
**Pull request by tlouisse**
Fixes https://github.com/ing-bank/lion/issues/112

### CODE REVIEW

**Comment by jorenbroekema** [comment]
Since no issue was mentioned, can you provide a use case for this where supporting TemplateResult in SlotMixin is important?

**Comment by tlouisse** [comment]
> Since no issue was mentioned, can you provide a use case for this where supporting TemplateResult in SlotMixin is important?

Ah, right. See https://github.com/ing-bank/lion/issues/112
It's an improvement of readability/maintainability and Developer Experience. One of the reasons that we don't construct our shadow dom like this.

**Comment by bashmish** [comment]
We are closing this for now. Can you please talk to @thatianamg ?

**Comment by daKmoR** [comment]
Let’s use renderOffline (rename to renderAsNode) instead

**Pull request closed without merging**
