### PR TITLE
exposed property and PropertyDeclarations from lit-element

### PR DESCRIPTION
**Pull request by sebastiangora**
It would be nice to have access to property decorator and PropertyDeclarations object for typing in typescript files

### CODE REVIEW

**Comment by daKmoR** [comment]
thank you for your contribution ❤️ 

we cherry picked and released it via https://github.com/ing-bank/lion/pull/47

**Comment by daKmoR** [comment]
@sebastiangora just a heads up but we will need to remove the `PropertyDeclarations` export again :see_no_evil:  it is "just" a type and therefore will not be available in "just" javascript

**Comment by sebastiangora** [comment]
ok, so we will use property decorator and remove PropertyDeclarations typings  from our project :)

**Comment by daKmoR** [comment]
for types you can still get them from lit-element directly... however you will always need to make sure you have exactly the same version we have or ignore eslint import for types :grimacing:

**Pull request closed without merging**
