### PR TITLE
[localize] Improve documentation

### PR DESCRIPTION
**Pull request by bashmish**
The documentation is currently very outdated, contains some very old APIs which are not supported, misleading recommendations and lacks some recent new features information.

### CODE REVIEW

**Comment by tlouisse** [comment]
Nice improvements 👍 

Could you also maybe add:
- the rationale behind the immutability of a namespace object (once a namespace is created, we cannot add extra data)?



Some nitpicking:
- Since 'data' is plural, I think we should change all occurences of 'data is' to 'data are'
- Can we add secure addresses as examples? `http` -> `https`

**Comment by tlouisse** [comment]
**Some more nitpicking with regard to the lifeycle callbacks...**

For me it's not totally clear what the difference is between `onLocaleChanged` and `onLocaleUpdated`.

```js
// LocalizeMixin

onLocaleChanged() {
  this.localizeNamespacesLoaded = localize.loadNamespaces(this.__getUniqueNamespaces());
  this.onLocaleUpdated();
  this.requestUpdate();
}

// eslint-disable-next-line class-methods-use-this
onLocaleUpdated() {}
```
When looking above code, the difference I see is that `this.requestUpdate()` is called after `this.requestUpdate()` and `localeChanged` before(keeping in mind subclassers call `super.onLocaleChanged`). Is this right and does this difference require separate callbacks?

Would it be an idea to change the current three callbacks to these two:
- `onLocaleUpdated` (it has the same as current onLocaleChanged and current onLocaleUpdated could be omitted)
-  `onLocaleFirstUpdated` (it is the same as current localeReady, but from the name its purpose is more clear)

**Comment by bashmish** [comment]
> Some nitpicking:
> 
> * Since 'data' is plural, I think we should change all occurences of 'data is' to 'data are'
> * Can we add secure addresses as examples? `http` -> `https`

Good ones, fixed now 💪 

> Could you also maybe add:
> 
> the rationale behind the immutability of a namespace object (once a namespace is created, we cannot add extra data)?

Rationale will be in another MR, with a lot of extra info as well.

**Comment by tlouisse** [comment]
> > Some nitpicking:
> > 
> > * Since 'data' is plural, I think we should change all occurences of 'data is' to 'data are'
> > * Can we add secure addresses as examples? `http` -> `https`
> 
> Good ones, fixed now 💪
> 
> > Could you also maybe add:
> > the rationale behind the immutability of a namespace object (once a namespace is created, we cannot add extra data)?
> 
> Rationale is in [another MR](https://github.com/ing-bank/lion/pull/216) with a lot of extra info.

Thanks!

**Pull request merged**
