### PR TITLE
Fix/date validators

### PR DESCRIPTION
**Pull request by vlaraort**
closes https://github.com/ing-bank/lion/issues/1076

## What I did

1. Serialize the input values into the date validators, so it doesn't give false errors when the inputs has a time different than 00:00:00

2. Tests

### CODE REVIEW

**Comment by tlouisse** [comment]
Looks good 👍 Could you  fix the lint errors?
Unfortunately the tests fail on Webkit (Safari) Are you able to fix those maybe?

**Comment by vlaraort** [comment]
Sure, fixed, now it's ready. Do I have to do something with the versions or changelogs?

**Comment by tlouisse** [comment]
> Sure @tlouisse , fixed, now it's ready. Do I have to do something with the versions or changelogs?, from my point of view, I should run changeset as patch version for the form-core package. Is this correct?

Hey, sorry for the late response, I became ill last week. Thanks for the fixes and you are right about the changesets 👍 
(or we can also add them if you want)

**Comment by vlaraort** [comment]
I hope you are better @tlouisse , you have the changeset done, it's fine to merge now?

**Comment by tlouisse** [comment]
> I hope you are better @tlouisse , you have the changeset done, it's fine to merge now?

Thanks, I am. Looks good now, wel will squash all commits into one when we merge it 👍 

It somehow still complains about license/cli, although it said `All committers have signed the CLA.`
If you can't fix this on your end, I will make a separate pull request in your name and merge that into master

**Comment by daKmoR** [comment]
the "problem" is that some commits are by `victorlara@outlook.com` which is not associated with any github account.

so either add that email to your github account or make sure all commits are with for example `redteamwins@gmail.com` (which is an email associated with your github account)

**Comment by vlaraort** [comment]
Yup sorry, Thank you for the info @daKmoR , I made kind a mess with my gitconfig. I have edited the author of the commits and now is reaady :)

**Review by tlouisse — APPROVED** [review]

**Comment by tlouisse** [comment]
It's merged, @vlaraort .  Thanks again

**Pull request merged**
