### PR TITLE
fix: [localize] date formatting forced #296

### PR DESCRIPTION
**Pull request by r4zorgeek**
also added test cases and storybook demo.

### CODE REVIEW

**Comment by r4zorgeek** [comment]
@LarsDenBakker Hey its been a couple of days since I committed can you please review it?

**Comment by jorenbroekema** [comment]
Hey @r4zorgeek , is this tied to an issue? Because I am not entirely sure about this PR. 

Basically, PR does two things:
- Allow people to format without a certain part (day, month, year), this is intended.
- Remove our defaults in a breaking way (not intended, see example below).

Why is it breaking? The failing test shows it actually.
For example:
```js
formatDate(new Date('2017/06/15'), { locale: 'en-US' });
```
outputs 6/15/2017 instead of 06/15/2017 now, and this is breaking behavior.

So basically, I think there should be some discussion / research.

In my opinion:
I agree we should allow people to format without certain parts (day, month, year). The way we set "smart defaults" overrides this Intl feature and that's in my opinion a "bug" on our part, I think it was unintended and even if it was intended, I think it's too opinionated that we do this. However, as I said before, it is a breaking change and requires people extending lion to change their code if they want the same output as they had before. So we should definitely be mindful about that and release this with the information that this is breaking. I don't think backwards compatibility is necessary.

If it was up to me, we change the tests to `6/15/2017` and change commit to `fix(localize): remove defaults that prevented excluding parts (BREAKING)`. Then on our extension layer we can add these defaults back in if we still feel like we should enforce it, but then we should add an API that allows people to exclude those parts, as a feature. 

Proposal for API on our extension layer could be:
```js
formatDate(new Date(), { 
  weekday: 'long',
  year: 'numeric',
  month: 'long',
  day: 'none'
});
```
Where under the hood we take 'none' and disable the defaults we set for that specific part (day, month, year), so that way it gets excluded entirely.

note: semver/conventional commits allow for specifying breaking changes with a commit: `BREAKING CHANGE(localize): remove defaults that prevented excluding parts` but im not sure what lerna would do with this, usually this is a major bump so I'm not sure if it would release v1, that would be very bad :P since we are still in alpha. @daKmoR ?

Sorry for the long message, the PR seems simple at the start, but has side effects which are breaking, so we have to think carefully about it :)

**Comment by gerjanvangeest** [comment]
We can do the following to prevent the failing tests:

```js
  if (!options.day && !options.month && !options.year) {
    formatOptions.year = 'numeric';
    formatOptions.month = '2-digit';
    formatOptions.day = '2-digit';
  }
```

But I agree with @jorenbroekema that the change is breaking, but we will fix that on our extension layer.

**Comment by r4zorgeek** [comment]
@jorenbroekema @gerjanvangeest Thanks for your great comments. Can you please tell how should I proceed further. Should I add the code which is suggested by @gerjanvangeest

**Comment by gerjanvangeest** [comment]
> @jorenbroekema @gerjanvangeest Thanks for your great comments. Can you please tell how should I proceed further. Should I add the code which is suggested by @gerjanvangeest

Yes please

**Pull request merged**
