### PR TITLE
Update eslint plugins and configs

### PR DESCRIPTION
**Pull request by koddsson**
## What I did

1. Updated some eslint plugins and configs in anticipation for upgrading to eslint 9

### CODE REVIEW

**Comment by gerjanvangeest** [comment]
Just wondering why did you downgrade `eslint-plugin-lit-a11y` again?

**Review by gerjanvangeest — APPROVED** [review]

**Comment by koddsson** [comment]
> Just wondering why did you downgrade `eslint-plugin-lit-a11y` again?

It was a breaking change that required me to either fix the new violations or mark those lines as disabled but I couldn't figure it out.

**Comment by gerjanvangeest** [comment]
> It was a breaking change that required me to either fix the new violations or mark those lines as disabled but I couldn't figure it out.

Ah oke, let me see if i can figure it out :)

**Comment by gerjanvangeest** [comment]
@koddsson got it working:
https://github.com/ing-bank/lion/pull/2259

**Pull request merged**
