### PR TITLE
chore: demo for issue recreate combobox in dialog

### PR DESCRIPTION
**Pull request by palash2601**
## What I did

1. Recreated issue reported in https://github.com/ing-bank/lion/issues/1216

### CODE REVIEW

**Comment by tlouisse** [comment]
Possibly be solved by https://github.com/ing-bank/lion/pull/1265
@palash2601 Could you check if this is the case?

**Comment by palash2601** [comment]
Hey @tlouisse ,

I have tried adding the changes for `SyncUpdatableMixin` in this branch and still getting the same error.

Can you check once?

**Comment by tlouisse** [comment]
> Hey @tlouisse ,
> 
> I have tried adding the changes for `SyncUpdatableMixin` in this branch and still getting the same error.
> 
> Can you check once?

@palash2601 No, the registration being canceled on disconnected is still an issue.
I thought it would solve the test you showed me a week ago (with combobox option waiting for el.registrationComplete before being transfered)

**Comment by palash2601** [comment]
> > Hey @tlouisse ,
> > I have tried adding the changes for `SyncUpdatableMixin` in this branch and still getting the same error.
> > Can you check once?
> 
> @palash2601 No, the registration being canceled on disconnected is still an issue.
> I thought it would solve the test you showed me a week ago (with combobox option waiting for el.registrationComplete before being transfered)

Hey @tlouisse, yes the issue with combobox works. We wait for that change to be ready for our use

**Comment by tlouisse** [comment]
> > > Hey @tlouisse ,
> > > I have tried adding the changes for `SyncUpdatableMixin` in this branch and still getting the same error.
> > > Can you check once?
> > 
> > 
> > @palash2601 No, the registration being canceled on disconnected is still an issue.
> > I thought it would solve the test you showed me a week ago (with combobox option waiting for el.registrationComplete before being transfered)
> 
> Hey @tlouisse, yes the issue with combobox works. We wait for that change to be ready for our use

Nice 👍 I expect a release beginning next week

**Comment by tlouisse** [comment]
Fixed in https://github.com/ing-bank/lion/pull/1287

**Pull request closed without merging**
