### PR TITLE
[select-rich] Add index.js with class export

### PR DESCRIPTION
**Pull request by jorenbroekema**

### CODE REVIEW

**Comment by jorenbroekema** [comment]
Uhh it's not prettier formatted I guess. I only have nano as my editor atm since I'm trying to get my new machine working so maybe someone else can quickly fix it :P

**Comment by bashmish** [comment]
@jorenbroekema done. Also please use `fix` for such changes, because it changes the package production code.

**Comment by jorenbroekema** [comment]
Aah true, good point

**Comment by daKmoR** [comment]
should also have added
```
main: "index.js",
module: "index.js",
```
to `package.json` right?

**Comment by jorenbroekema** [comment]
I think it's already there right?

**Comment by daKmoR** [comment]
yeah true 👍

**Pull request merged**
