### PR TITLE
Exclusive accordion

### PR DESCRIPTION
**Pull request by johncliffrule**
This PR adds a new property called "exclusive" , which when enabled allows only one accordion to be open at any given time.

### CODE REVIEW

**Review by gerjanvangeest — CHANGES_REQUESTED** [review]
@johncliffrule thanks for the addition to the accordion 💪 

Can you add some tests for `exclusive`?
Can you also add a changeset (`npm run changeset`) to which helps us to add this change to the changelog.

**Comment by johncliffrule** [comment]
> @johncliffrule thanks for the addition to the accordion 💪
> 
> Can you add some tests for `exclusive`? Can you also add a changeset (`npm run changeset`) to which helps us to add this change to the changelog.

Hi, you can now see tests added
And for changeset I see this message
image
 **_WARNING: Releasing a major version for @lion/ui will be its first major release.
🦋  If you are unsure if this is correct, contact the package's maintainers before committing this changeset._**

Is this fine?

**Comment by johncliffrule** [comment]
> The app fails to render the dynamic examples when running via `npm run start` when navigating to `http://localhost:8001/components/accordion/use-cases/`

@tlouisse did you check this?

**Comment by tlouisse** [comment]
> > The app fails to render the dynamic examples when running via `npm run start` when navigating to `http://localhost:8001/components/accordion/use-cases/`
> 
> @tlouisse did you check this?

Yes, I just pushed the fix and a changeset 👍

**Review by gerjanvangeest — APPROVED** [review]

**Pull request merged**
